### ISSUE TITLE
Tambahkan fitur "saran entri lain yang mirip" khusus pengguna

### ISSUE THREAD

**Issue by laymonage** [laymonage/kbbi-python#13]
Terdapat fitur khusus pengguna di mana ketika pengguna mencari entri yang tidak ditemukan, sistem KBBI Daring akan menampilkan saran entri lain yang mirip.

Contoh:

https://kbbi.kemdikbud.go.id/entri/huk

Terdapat beberapa saran, seperti "auk", "buk (1)", "buk (2)", dan seterusnya. Sepertinya informasi ini akan sangat berguna, terutama jika terdapat saltik dalam masukan pengguna.

Namun, ada beberapa hal yang perlu diperhatikan dalam mengimplementasikan ini. Saat ini, kita menaikkan `TidakDitemukan(Galat)` ketika entri tidak ditemukan. Jika kita mengimplementasikan hal ini, apakah galat tersebut tetap dinaikkan? Jika ya, di mana kita akan menempatkan informasi saran tersebut? Lalu, apakah akan ada serialisasi JSON-nya? Jika tidak, apakah memang menghilangkan galat tersebut merupakan pilihan yang tepat?

**Comment by maulana20** [comment]
Hallo mas @laymonage .. untuk entry yang tidak di temukan di kbbi hasil pencarian tidak menampilkan saran seperti yang di issuekan mas di atas.

![image](https://user-images.githubusercontent.com/11070656/78623378-b639b080-78b1-11ea-904e-507cc3c7de81.png)

**Comment by laymonage** [comment]
Halo Mas @maulana20, sepertinya Mas belum masuk (*log in*) ke sistem KBBI Daring ya? Fitur yang dideskripsikan pada isu ini memang hanya tersedia untuk pengguna. Tampilannya seperti berikut.

![image](https://user-images.githubusercontent.com/6379424/78624006-d28a1d00-78b2-11ea-9385-851901aa0a43.png)
