### ISSUE TITLE
Fungsi "TidakDitemukan" Tidak Tersedia

### ISSUE THREAD

**Issue by wildangunawan** [laymonage/kbbi-python#21]
Halo,

Saya sedang mengembangkan sebuah aplikasi menggunakan KBBI Python. Namun saat mengimpor fungsi "TidakDitemukan", saya mendapatkan error sebagai berikut:
```
Traceback (most recent call last):
File "app.py", line 2, in <module>
from kbbi import TidakDitemukan
ImportError: cannot import name 'TidakDitemukan'
```

Saya memiliki versi terbaru yaitu 0.4.2 yang diunduh melalui PyPi.
Mohon bantuannya jika saya mengalami salah ketik.

Terima kasih!

**Comment by wildangunawan** [comment]
Informasi tambahan:
Sepertinya fungsi TidakDitemukan berada di dalam fungsi/kelas KBBI (mohon maaf jika salah sebab saya kurang mahir dalam pemrograman berorientasikan objek). Saya dapat mengakses fungsi TidakDitemukan dengan cara sbb.:

```
from kbbi import KBBI

try:
	kata = KBBI('a-beta')
except KBBI.TidakDitemukan as e:
	print(e)
```

Hal ini berbeda dengan apa yang tertulis dalam [README.md](https://github.com/laymonage/kbbi-python/blob/master/README.md).

Terima kasih!

**Comment by wildangunawan** [comment]
Sepertinya permasalahan ini hanya terjadi pada sistem lokal saya saja.
Saya dapat mengimpor TidakDitemukan tanpa error pada peladen "server" saya.

Sistem lokal saya menggunakan Python 3.5.3 sedangkan pada peladen "server" saya menggunakan Python 3.6.9.
Saya akan menutup isu ini sekarang. Mohon maaf atas ketidaknyamanannya.

**Comment by laymonage** [comment]
Halo Mas @wildangunawan, terima kasih atas laporannya. Mohon maaf apabila dokumentasinya masih sangat minim. Betul, isu tersebut sepertinya muncul karena Mas menggunakan Python 3.5.

Terdapat perubahan yang cukup signifikan antara versi `0.4.0` dengan versi sebelumnya (`0.3.2`). Sejak versi `0.4.0`, `kbbi-python` hanya mendukung Python >= 3.6 karena saya mulai [menggunakan f-string](https://github.com/laymonage/kbbi-python/commit/6bd94218318281c4089c1ea862155ea988621ee4) yang hanya tersedia pada Python >= 3.6.

Pada versi `0.4.0`, saya juga [mengeluarkan *class* galat ke luar *class* `KBBI`](https://github.com/laymonage/kbbi-python/commit/280cec42a36b8490a5889a40cffeb1b3f6d219aa). Saya berencana menambahkan *class-class* galat lagi (misalnya untuk masalah autentikasi), sehingga sepertinya kodenya akan lebih rapi jika *class-class* tersebut diletakkan di luar.

`pip` otomatis mencari versi yang kompatibel dengan versi Python yang digunakan, sehingga mungkin yang terinstal di sistem lokal Mas adalah versi sebelum `0.4.0`. Python 3.5 sudah tidak punya pembaruan dalam bentuk *binary* lagi. Namun, Python 3.5 baru akan "mati" pada [September tahun ini](https://devguide.python.org/#status-of-python-branches), jadi sepertinya maklum apabila masih ada yang pakai.

Terima kasih atas laporannya, Mas. Semoga bisa membantu orang lain yang punya masalah serupa. Apabila masih ada kendala, jangan sungkan untuk buat isu lagi. :pray:
